import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ReactTypingEffect from "react-typing-effect";
import { Button, TextArea } from "../components";

const UGLY_WORDS = ["BOLSONARO", "SUA MÃE", "O FDP DO PUTIN"];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Deixe seu link feio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Deixe seu link mais feio que <br />
          <ReactTypingEffect
            eraseSpeed={100}
            typingDelay={100}
            text={UGLY_WORDS}
          />
        </h1>

        <TextArea
          placeholder="Ola porra"
          label="cole seu link aqui"
          type="text"
        />

        <Button>Enviar</Button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.paypal.com/donate/?hosted_button_id=Q5DYVYRNFDW5E"
          target="_blank"
          rel="noopener noreferrer"
        >
          me pague um café
        </a>
      </footer>
    </div>
  );
};

export default Home;
